config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  resources :projects, only: [ :index, :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many_attached :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homepage</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>My story</h1>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1472712739516-7ad2b786e1f7?q=80&w=2938&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container">
    <%= image_tag "https://avatars.githubusercontent.com/u/144142847?v=4", class: "avatar-large mb-2", alt: "avatar-large" %>
    <div class="container-text">
      <h1>Rico Paum</h1>
      <p class="mt-2">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus praesentium cumque, expedita fugiat enim nam.</p>
    </div>
  </div>
</div>


<%# https://avatars.githubusercontent.com/u/144142847?v=4 %>

app/views/projects/index.html.erb
<div class="container mt-3">
  <% @projects.each do |project| %>
    <%= link_to project_path(project), class: "card-link" do %>
      <div class="card-project">
        <%= cl_image_tag(project.photos.first.key) if project.photos.attached? %>
        <div class="card-project-infos">
          <h2><%= project.name %></h2>
          <p>End goal: <strong><%= project.end_goal %></strong></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div style="border-top:1px solid white;">
  <div class="container project-info">
    <div class="d-flex justify-content-center">
     <h1><%= @project.name %></h1>
    </div>
    <div class="d-flex justify-content-center">
      <p class="mx-1"><%= @project.start_date %></p>
      <p class="mx-1"><strong> - </strong></p>
      <p class="mx-1"><%= @project.end_date %></p>
    </div>
    <div>
    <p><%= @project.end_goal %></p>
    <p><%= @project.description %></p>
    </div>
  </div>
  <div class="container container-pictures">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carousel<%= @project.id %>" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carousel<%= @project.id %>" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carousel<%= @project.id %>" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carousel<%= @project.id %>" data-bs-slide-to="3" aria-label="Slide 4"></button>
        <button type="button" data-bs-target="#carousel<%= @project.id %>" data-bs-slide-to="4" aria-label="Slide 5"></button>
        <button type="button" data-bs-target="#carousel<%= @project.id %>" data-bs-slide-to="5" aria-label="Slide 6"></button>
        <button type="button" data-bs-target="#carousel<%= @project.id %>" data-bs-slide-to="6" aria-label="Slide 7"></button>
        <button type="button" data-bs-target="#carousel<%= @project.id %>" data-bs-slide-to="7" aria-label="Slide 8"></button>
      </div>
      <div class="carousel-inner">
        <% @project.photos.each_with_index do |photo, index| %>
          <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
            <%= cl_image_tag(photo.key) %>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <div class="container-fluid">
    <div>
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "Homepage", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About me", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My projects", projects_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact me", contact_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>